---
language: node_js
node_js:
  - "10"

dist: xenial

addons:
  chrome: stable
  apt:
    packages:
      - xvfb

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

script:
  - npm test
install:
  - yarn install --non-interactive
  - cd electron-app && yarn install --non-interactive
  - 'export DISPLAY='':99.0'''
  - 'Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &'
  - cd electron-app && yarn install --non-interactive
  - cd electron-app && yarn install --non-interactive
  - cd electron-app && yarn install --non-interactive
  - cd electron-app && yarn install --non-interactive
  - cd electron-app && yarn install --non-interactive
